# Generated by Django 5.2.4 on 2025-08-04 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tipo_movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipomovimentacao'),
        ),
    ]
