# Generated by Django 5.2.4 on 2025-08-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movimentacao_tipomovimentacao_delete_receita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.CharField(max_length=10),
        ),
    ]
