# Generated by Django 5.2.4 on 2025-08-04 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_alter_movimentacao_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name_plural': 'movimentações'},
        ),
        migrations.AlterModelOptions(
            name='tipomovimentacao',
            options={'verbose_name_plural': 'tipo movimentações'},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
    ]
