# Generated by Django 5.2.4 on 2025-08-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movimentacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
