# Generated by Django 5.2.4 on 2025-08-19 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movimentacao_data_alter_movimentacao_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='TipoMovimentacao',
            new_name='TransactionType',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='tipo_movimentacao',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('receita', 'Receita'), ('gasto', 'Gasto')], max_length=10)),
                ('description', models.CharField(max_length=250)),
                ('payment_method', models.CharField(max_length=10)),
                ('date', models.DateField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
            options={
                'verbose_name_plural': 'transações',
            },
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Movimentacao',
        ),
    ]
