# Generated by Django 5.2.4 on 2025-08-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_options_alter_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credito', 'Crédito'), ('debito', 'Debito')], max_length=10),
        ),
    ]
