# Generated by Django 5.2.4 on 2025-08-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
