# Generated by Django 5.2.4 on 2025-08-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_transactiontype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
